/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Paola
 */
public class Gui_VentanaPrincipal extends javax.swing.JFrame {

    public Gui_login gui_login;
    /**
     * Creates new form Gui_VentanaPrincipal
     */
    public Gui_VentanaPrincipal(Gui_login login) {
        initComponents();
        this.gui_login = login;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonEmpleados = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jButtonPedidos = new javax.swing.JButton();
        jButtonVenta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal SG_REST");

        jPanel1.setLayout(null);

        jButtonEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1 persona.png"))); // NOI18N
        jButtonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEmpleados);
        jButtonEmpleados.setBounds(50, 10, 130, 130);

        jButtonProductos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1 productos.png"))); // NOI18N
        jButtonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonProductos);
        jButtonProductos.setBounds(220, 10, 140, 130);

        jButtonPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1 pedido.jpg"))); // NOI18N
        jButtonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPedidos);
        jButtonPedidos.setBounds(400, 10, 140, 130);

        jButtonVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1 venta.png"))); // NOI18N
        jButtonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVenta);
        jButtonVenta.setBounds(50, 180, 130, 120);

        jLabel3.setText("Empleados");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 140, 70, 14);

        jLabel1.setText("Items del Menú");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 140, 90, 14);

        jLabel2.setText("Pedido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 140, 41, 14);

        jLabel4.setText("Caja");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 310, 22, 14);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPanel1.add(jLabelFondo);
        jLabelFondo.setBounds(0, 0, 590, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpleadosActionPerformed
        // TODO add your handling code here:
        try{
         Gui_empleado empleado =new Gui_empleado(this);
    
         empleado.setVisible(true);
         this.dispose();
         
       }catch(Exception e){}
      
    }//GEN-LAST:event_jButtonEmpleadosActionPerformed

    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed
        // TODO add your handling code here:
         try{
         Gui_producto producto =new Gui_producto(this);
    
         producto.show();
         producto.setLocation(50, 5);
         this.dispose();
       }catch(Exception e){}
    }//GEN-LAST:event_jButtonProductosActionPerformed

    private void jButtonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidosActionPerformed
        // TODO add your handling code here:
         try{
         Gui_pedido pedido =new Gui_pedido(this);
    
         pedido.show();
         pedido.setLocation(50, 5);
         this.dispose();
       }catch(Exception e){}
        
    }//GEN-LAST:event_jButtonPedidosActionPerformed

    private void jButtonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentaActionPerformed
         // TODO add your handling code here:
         try{
         Gui_venta venta = new Gui_venta(this);
         venta.setVisible(true);
         this.dispose();
       }catch(Exception e){}
    }//GEN-LAST:event_jButtonVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_VentanaPrincipal(new Gui_login ()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEmpleados;
    private javax.swing.JButton jButtonPedidos;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFondo;
    public static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
