/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Empleado;
import Clases.EstadoPedido;
import Clases.Mesa;
import Clases.Pedido;
import Clases.Producto;
//import Clases.ProductoPedido;
//import Clases.ProductoPedidoPK;
import Controladores.EmpleadoJpaController;
import Controladores.EstadoPedidoJpaController;
import Controladores.MesaJpaController;
import Controladores.PedidoJpaController;
import Controladores.ProductoJpaController;
//import Controladores.ProductoPedidoJpaController;
import Controladores.exceptions.*;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paola
 */
public class Gui_pedido extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form empleado
     */
    public Gui_pedido(Gui_VentanaPrincipal principal) {
        initComponents();
        deshabilitar();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMesa = new javax.swing.JTextField();
        jPanelProductos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButtonAgregarProducto = new javax.swing.JButton();
        jButtonEliminarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jButtonagregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jLabelHoraInicio = new javax.swing.JLabel();
        jLabelNumPedido = new javax.swing.JLabel();
        jTextFieldMesero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelHoraFin = new javax.swing.JLabel();

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel1.setText("Numero de Pedido:");

        jLabel2.setText("Numero de mesa:");

        jLabel.setText("Id del Mesero:");

        jLabel4.setText("Hora Inicio del Pedido:");

        jTextFieldMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMesaKeyTyped(evt);
            }
        });

        jPanelProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos del pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel7.setText("Producto: ");

        jComboBox2.setToolTipText("");

        jButtonAgregarProducto.setText("Agregar al pedido");
        jButtonAgregarProducto.setToolTipText("");
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });

        jButtonEliminarProducto.setText("Eliminar del pedido");
        jButtonEliminarProducto.setToolTipText("");

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        jLabel8.setText("Cantidad:");

        jTextFieldCantidad.setToolTipText("");
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });

        jButtonagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/16 (Save).jpg"))); // NOI18N
        jButtonagregar.setText("Realizar Pedido");
        jButtonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductosLayout = new javax.swing.GroupLayout(jPanelProductos);
        jPanelProductos.setLayout(jPanelProductosLayout);
        jPanelProductosLayout.setHorizontalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductosLayout.createSequentialGroup()
                        .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                            .addGroup(jPanelProductosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProductosLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jButtonAgregarProducto))
                            .addGroup(jPanelProductosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(jButtonEliminarProducto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonagregar)
                        .addGap(66, 66, 66))))
        );
        jPanelProductosLayout.setVerticalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarProducto)
                    .addComponent(jButtonEliminarProducto)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonagregar)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/16 (Search).jpg"))); // NOI18N
        jButtonBuscar.setText("Buscar Pedido");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3 modificar.png"))); // NOI18N
        jButtonModificar.setText("Modificar Pedido");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/16 (Delete).jpg"))); // NOI18N
        jButtonSalir.setText("salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3 eliminar.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar Pedido");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wzdelete.jpg"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3 anadir.png"))); // NOI18N
        jButtonNuevo.setText("nuevo");
        jButtonNuevo.setToolTipText("");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButtonCancelar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonModificar)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonEliminar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(159, 159, 159))
        );

        jTextFieldMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMeseroActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora Fin del Pedido:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel)
                        .addComponent(jLabelNumPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelHoraInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabelHoraFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelNumPedido.getAccessibleContext().setAccessibleName("jLabelNumPedido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(567, 567, 567))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char car=evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')&&(car<' '||car>' ')) evt.consume();

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        habilitar();
        
        Date fechaActual = new Date();
        
        SimpleDateFormat horaFormato = new SimpleDateFormat("hh:mm:ss");
        String horaInicio = horaFormato.format(fechaActual);
        this.jLabelHoraInicio.setText(horaInicio);
        
        
        
        EntityManagerFactory emf1 = Persistence.createEntityManagerFactory("SG-RESTPU");
        
        PedidoJpaController daoPedido = new PedidoJpaController(emf1);
        
        String numPedido = Integer.toString(daoPedido.getPedidoCount() + 1);
        
        this.jLabelNumPedido.setText(numPedido);
        
        
        this.jComboBox2.setModel(this.obtenerProductos());
        
        
        //this.jComboBox2.setModel(this.obtenerProductos(this.jComboBox.getSelectedItem().toString()));
        
        /*this.jComboBox1.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if ( e.getStateChange() == ItemEvent.SELECTED ) 
                {
                    // los nuevos registros son agregados al MODEL del JCombo HIJO
                    String item = jComboBox1.getSelectedItem().toString();
                    jComboBox2.setModel( obtenerProductos(item) );
                }
            }
            });*/
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    public DefaultComboBoxModel obtenerProductos(){
        
        DefaultComboBoxModel listmModel = new DefaultComboBoxModel();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("SG-RESTPU");
        
        ProductoJpaController daoProducto = new ProductoJpaController(emf);
        
        List<Producto> listaProductos = daoProducto.findProductoEntities();
        
       
        for (int i = 0; i < listaProductos.size(); i++) {
            listmModel.addElement(listaProductos.get(i).getNombre());
           
        }
        
        return listmModel;    
        
    }
    
   
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        botones();
        deshabilitar();
        DefaultTableModel modelo = (DefaultTableModel) jTableProductos.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
 
        
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        try{
         Gui_VentanaPrincipal gui_principal =new Gui_VentanaPrincipal(new Gui_login());
    
         gui_principal.show();
         gui_principal.setLocation(50, 5);
         this.dispose();
       }catch(Exception e){}
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        //variables para el pedido
        /*
        int numPedido = Integer.parseInt(this.jLabelNumPedido.getText());
        String idMesero = this.jTextFieldMesero.getText();
        int numMesa = Integer.parseInt(this.jTextFieldMesa.getText());
        Date horaFinal = new Date();
        Date horaInicio = null;
        
        
        SimpleDateFormat formato = new SimpleDateFormat("hh:mm:ss");
        try {
            horaInicio = formato.parse(this.jLabelHoraInicio.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Gui_pedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Pedido pedido = new Pedido();
        
        pedido.setNumPedido(numPedido);
        pedido.setHoraFinalPedido(horaFinal);
        pedido.setHoraInicioPedido(horaInicio);
        pedido.setNumMesa(numMesa);
             
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("SG_RESTPU");
        EmpleadoJpaController daoEmpleado = new EmpleadoJpaController(emf);
        Empleado empleado = daoEmpleado.findEmpleado(idMesero);
        pedido.setIdEmpleado(empleado);
        
        
        
        
        PedidoJpaController daoPedido = new PedidoJpaController(emf);
        
        
        ProductoPedidoJpaController daoProductoPedido = new ProductoPedidoJpaController(emf);
        
        ProductoPedido productoPedido = new ProductoPedido();
        ProductoPedidoPK productoPedidopk = new ProductoPedidoPK();
        
        try {
            if (verificarCamposVacios() == false) {
                daoPedido.edit(pedido);
                deshabilitar();
                JOptionPane.showMessageDialog(null, "El pedido se agrego exitosamente", "Exito!", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Llene los datos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                limpiar();
            }
            
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Llene los datos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
        } catch (Exception ex) {
            Logger.getLogger(Gui_empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        for (int i = 0; i < modelo.getRowCount(); i++) {
            
            String nombreProducto = modelo.getValueAt(i, 0).toString();
            String cantidadProducto = modelo.getValueAt(i, 1).toString();
            
            System.out.println(nombreProducto + cantidadProducto);
                    
            ProductoJpaController daoProducto = new ProductoJpaController(emf);
            List<Producto> producto = daoProducto.findProductoNombre(nombreProducto);
            
            Producto producto1;
            
            producto1 = producto.get(0);
            
            
            productoPedido.setProducto(producto1);
            productoPedido.setCantProductos(Integer.parseInt(cantidadProducto));
            productoPedido.setPedido(pedido);
            
            
            
            try {
                daoProductoPedido.edit(productoPedido);
            } catch (NonexistentEntityException ex) {
                System.out.println("1");
            } catch (PreexistingEntityException ex) {
                System.out.println("2");
            } catch (Exception ex) {
                System.out.println("3");
            }
            
        }  */
            
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       
        
        String id = JOptionPane.showInputDialog(null, "Ingrese el del pedido que desea buscar", "Buscar", JOptionPane.QUESTION_MESSAGE);

        int idParse = Integer.parseInt(id);
        //Se crea en EntityManagerFactory con el nombre de nuestra unidad de persistencia
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("SG-RESTPU");
        
        
        PedidoJpaController daoPedido = new PedidoJpaController(emf);
        
        try{
            Pedido pedido = daoPedido.findPedido(idParse);
            
           
            ArrayList<Producto> productoPedido = (ArrayList)pedido.getProductoCollection();
            this.modelo = (DefaultTableModel) jTableProductos.getModel();
            
            for (int i = 0; i < productoPedido.size(); i++) {
                
                Producto pro = productoPedido.get(i);
                Vector<String> vector = new Vector<String>();
                
                String producto = pro.getNombre();
                vector.add(producto);
               /* String cantidad = Integer.toString(productoPedido.get(i).);
                vector.add(cantidad);*/
                
                this.modelo.addRow(vector);
            }
            
        
        
            
           
            this.jLabelNumPedido.setText(Integer.toString(pedido.getNumPedido()));
            
                    
            SimpleDateFormat horaFormato = new SimpleDateFormat("hh:mm:ss");
            String horaInicio = horaFormato.format(pedido.getHoraInicioPedido());
            this.jLabelHoraInicio.setText(horaInicio);
            
            String horaFin = horaFormato.format(pedido.getHoraFinalPedido());
            this.jLabelHoraFin.setText(horaFin);
            
            this.jTextFieldMesa.setText(Integer.toString(pedido.getNumMesa().getNumMesa()));
            
            this.jTextFieldMesero.setText(pedido.getIdEmpleado().getIdentificacion());

            
            
            
            
            this.jButtonagregar.setEnabled(false);
            this.jButtonBuscar.setEnabled(false);
            this.jButtonModificar.setEnabled(true);
            this.jButtonEliminar.setEnabled(false);
            this.jButtonNuevo.setEnabled(false);
            
            habilitar();
            
            
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "El pedido no existe", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonagregarActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("SG-RESTPU");
        
        //variables para el pedido
        
        int numPedido = Integer.parseInt(this.jLabelNumPedido.getText());
        String idMesero = this.jTextFieldMesero.getText();
        int numMesa = Integer.parseInt(this.jTextFieldMesa.getText());
        MesaJpaController daoMesa = new MesaJpaController(emf);
        Mesa mesa = daoMesa.findMesa(numMesa);
        Date horaFinal = new Date();
        Date horaInicio = null;
        
        
        SimpleDateFormat formato = new SimpleDateFormat("hh:mm:ss");
        try {
            horaInicio = formato.parse(this.jLabelHoraInicio.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Gui_pedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Pedido pedido = new Pedido();
        
        pedido.setNumPedido(numPedido);
        pedido.setHoraFinalPedido(horaFinal);
        pedido.setHoraInicioPedido(horaInicio);
        pedido.setNumMesa(mesa);
        pedido.setProductoCollection(new ArrayList<Producto>());
             
        //id del mesero
        EmpleadoJpaController daoEmpleado = new EmpleadoJpaController(emf);
        Empleado empleado = daoEmpleado.findEmpleado(idMesero);
        pedido.setIdEmpleado(empleado);
        
        
        //estado del producto
        EstadoPedidoJpaController daoEstadoPedido = new EstadoPedidoJpaController(emf);
        EstadoPedido estadoPedido=daoEstadoPedido.findEstadoPedido(1);
        //
        pedido.setIdEstadoPedido(estadoPedido);
        
        ProductoJpaController daoProducto = new ProductoJpaController(emf);
        PedidoJpaController daoPedido = new PedidoJpaController(emf);
        Pedido pedido1 = new Pedido(numPedido);
        for (int i = 0; i < modelo.getRowCount(); i++) {
            
            String nombreProducto = modelo.getValueAt(i, 0).toString();
            String cantidadProducto = modelo.getValueAt(i, 1).toString();
            
            //Producto producto = daoProducto.findProductoNombre(nombreProducto);
            List<Producto> producto = daoProducto.findProductoNombre(nombreProducto);
            
            Producto producto1;
            
            producto1 = producto.get(0);
            System.err.println(producto1.getId());
            
            pedido.getProductoCollection().add(producto1);

        }
        
        
        try {
            if (verificarCamposVacios() == false) {
                daoPedido.create(pedido);
                deshabilitar();
                JOptionPane.showMessageDialog(null, "El pedido se agrego exitosamente", "Exito!", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Llene los datos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                limpiar();
            }
            
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Llene los datos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
        } catch (Exception ex) {
            Logger.getLogger(Gui_empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }//GEN-LAST:event_jButtonagregarActionPerformed

    public boolean verificarCamposVacios(){
        boolean var =false;
         
         if (jTextFieldCantidad.getText().equalsIgnoreCase("") || jTextFieldMesa.getText().equalsIgnoreCase("") ||
                 jTextFieldMesero.getText().equalsIgnoreCase("") || jComboBox2.getSelectedItem().toString().equalsIgnoreCase("") ) {
             
             var = true;             
         }
         
         return var;
    }
    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed
        String producto = this.jComboBox2.getSelectedItem().toString();
        String cantidad = this.jTextFieldCantidad.getText();
        
        
        
        this.modelo = (DefaultTableModel) jTableProductos.getModel();
               
        Object []object = new Object[2];
        
        object[0] = producto;
        object[1] = cantidad;
        
        this.modelo.addRow(object);
    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

    private void jTextFieldMesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMesaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
                  
        if(Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMesaKeyTyped

    private void jTextFieldMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMeseroActionPerformed

    private void jButtonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProductoActionPerformed
        int fila = jTableProductos.getSelectedRow();
        modelo.removeRow(fila);
    }//GEN-LAST:event_jButtonEliminarProductoActionPerformed

    File fichero;
     public void botones(){
        this.jButtonagregar.setEnabled(false);
        this.jButtonNuevo.setEnabled(true);
        this.jButtonBuscar.setEnabled(true);
        this.jButtonModificar.setEnabled(false);
        this.jButtonEliminar.setEnabled(false);
     }
    public void limpiar(){
        this.jTextFieldCantidad.setText("");
        this.jTextFieldMesa.setText("");
        generarTablaProductos();
        //this.jComboBox1.setSelectedIndex(0);
        
    }
    
    public void generarTablaProductos(){
        
    }
     public void habilitar(){
       this.jLabelNumPedido.setEnabled(true);
       this.jTextFieldMesa.setEnabled(true);
       this.jLabelHoraInicio.setEnabled(true);
       this.jTextFieldMesero.setEnabled(true);
       this.jButtonAgregarProducto.setEnabled(true);
       this.jButtonEliminarProducto.setEnabled(true);
       //this.jComboBox1.setEnabled(true);
       this.jComboBox2.setEnabled(true);
       this.jTextFieldCantidad.setEnabled(true);
       this.jTableProductos.setEnabled(true);
  }
    public void deshabilitar(){
       this.jLabelNumPedido.setEnabled(false);
       this.jTextFieldMesa.setEnabled(false);
       this.jTextFieldMesero.setEnabled(false);
       this.jLabelHoraInicio.setEnabled(false);
       this.jButtonAgregarProducto.setEnabled(false);
       this.jButtonEliminarProducto.setEnabled(false);
       
       this.jComboBox2.setEnabled(false);
       this.jTextFieldCantidad.setEnabled(false);
       this.jTableProductos.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_pedido(new Gui_VentanaPrincipal (new Gui_login())).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonEliminarProducto;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonagregar;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelHoraFin;
    private javax.swing.JLabel jLabelHoraInicio;
    private javax.swing.JLabel jLabelNumPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldMesa;
    private javax.swing.JTextField jTextFieldMesero;
    // End of variables declaration//GEN-END:variables
}
