/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
//
import Clases.Producto;
import Clases.ProductoFactura;
import Controladores.ProductoFacturaJpaController;
import Reportes.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Paola
 */
public class Gui_reportes extends javax.swing.JFrame {

    private Connection con = null;
    Conexion conexion =null;
            
    /**
     * Creates new form Gui_reportes
     */
    public Gui_reportes() {
        initComponents();
        conexion = new Conexion();
        
        con=conexion.getConexion();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        VisualizarMejorTop10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextAño = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelPestaña2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "01-Enero", "02-Febrero", "03-Marzo", "04-Abril", "05-Mayo", "06-Junio", "07-Julio", "08-Agosto ", "09-Septiembre", "10-Octubre", "11-Noviembre", "12-Diciembre" }));
        jComboBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxMes);
        jComboBoxMes.setBounds(150, 11, 120, 20);

        jLabel1.setText("Seleccione el mes: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(18, 14, 120, 14);

        VisualizarMejorTop10.setText("Visualizar");
        VisualizarMejorTop10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarMejorTop10ActionPerformed(evt);
            }
        });
        jPanel1.add(VisualizarMejorTop10);
        VisualizarMejorTop10.setBounds(350, 30, 100, 23);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 80, 680, 130);

        jLabel2.setText("Ingrese el año:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 110, 14);

        jTextAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAñoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextAño);
        jTextAño.setBounds(150, 40, 120, 30);

        jTabbedPane1.addTab("10 Items mas vendidos", jPanel1);

        jPanel2.setLayout(null);

        jLabel3.setText("Seleccione el semestre");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(39, 28, 108, 14);

        jPanelPestaña2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelPestaña2Layout = new javax.swing.GroupLayout(jPanelPestaña2);
        jPanelPestaña2.setLayout(jPanelPestaña2Layout);
        jPanelPestaña2Layout.setHorizontalGroup(
            jPanelPestaña2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPestaña2Layout.setVerticalGroup(
            jPanelPestaña2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelPestaña2);
        jPanelPestaña2.setBounds(10, 69, 690, 364);

        jTabbedPane1.addTab("10 Items menos vendidos", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    
    
    
    private void jComboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesActionPerformed

    private void VisualizarMejorTop10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarMejorTop10ActionPerformed
        // TODO add your handling code here:
        int castMes,castAño;
        String mes=this.jComboBoxMes.getSelectedItem().toString();
        
        String año= this.jTextAño.getText().trim();
        if (mes.equalsIgnoreCase("Seleccione") || año.equals("")){
        JOptionPane.showMessageDialog(null, "Llene los datos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);}
        else {
            mes = mes.substring(0, 2);
            castAño=Integer.parseInt(año);
            castMes=Integer.parseInt(mes);
            reporte10Mejores(castMes, castAño);
        }
    }//GEN-LAST:event_VisualizarMejorTop10ActionPerformed

    public void reporte10Mejores(int mes, int año) {
        try {
        JasperReport masterReport = null;
        File f= new File("Reportes/MasVendidos.jasper");
        try {
            masterReport = (JasperReport) JRLoader.loadObject(f);
          
        } catch (JRException ex) {
            System.out.println("error cargando reporte " + ex);
        }
         Map<String, Object> parametros = new HashMap();
            parametros.put("año", new Integer(año));
            parametros.put("mes", new Integer(mes));

            JasperPrint jasperPrint = JasperFillManager.fillReport(masterReport, parametros,con);
            System.out.println("pas");
            JasperViewer jViewer = new JasperViewer (jasperPrint, false);
            jViewer.setTitle("10 items mas vendidos");
            jViewer.setVisible(true);
        }catch(JRException ex){
            System.out.println("error generando reporte " + ex);
        }
            
       
        
    }
    private void jTextAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VisualizarMejorTop10;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelPestaña2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextAño;
    // End of variables declaration//GEN-END:variables
}
