/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Reportes.Reportes;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Paola
 */
public class Gui_VerReportes extends javax.swing.JFrame {

    Reportes reportes;
    Gui_VentanaPrincipalGerente gui_gerente = null;
    
    //ejemplo para traer los datos del usuario
//    String usuario = this.gui_gerente.gui_login.usuario;
    /**
     * Creates new form Gui_VerReportes
     */
    public Gui_VerReportes(Gui_VentanaPrincipalGerente gui_gerente){
        //(Gui_VentanaPrincipalGerente gui_gerente) {
        initComponents();
        reporteGerente();
        this.gui_gerente = gui_gerente;
        this.setLocationRelativeTo(null);
        this.jPanel3Contenedor.setVisible(false);
        System.err.println(this.gui_gerente.gui_login.usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxBusqueda = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jPanel3Contenedor = new javax.swing.JPanel();
        jPanelTop10 = new javax.swing.JPanel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAño = new javax.swing.JTextField();
        jButtonVisualizar = new javax.swing.JButton();
        jPanelMenosDeseados = new javax.swing.JPanel();
        jComboBoxSemestre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAño1 = new javax.swing.JTextField();
        jButtonVisualizarMenosDeseados = new javax.swing.JButton();
        jPanelEmpleadoMes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAño2 = new javax.swing.JTextField();
        jButtonVisualizarEmpleadoMes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxBusqueda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButtonBuscar)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscar)
                .addGap(7, 7, 7))
        );

        jPanel3Contenedor.setLayout(new java.awt.CardLayout());

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "01-Enero", "02-Febrero", "03-Marzo", "04-Abril", "05-Mayo", "06-Junio", "07-Julio", "08-Agosto", "09-Septiembre", "10-Octubre", "11-Noviembre", "12-Diciembre" }));
        jComboBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el mes:");

        jLabel2.setText("Ingreser el año:");

        jButtonVisualizar.setText("Visualizar");
        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTop10Layout = new javax.swing.GroupLayout(jPanelTop10);
        jPanelTop10.setLayout(jPanelTop10Layout);
        jPanelTop10Layout.setHorizontalGroup(
            jPanelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAño))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButtonVisualizar)
                .addGap(37, 37, 37))
        );
        jPanelTop10Layout.setVerticalGroup(
            jPanelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTop10Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTop10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTop10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTop10Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButtonVisualizar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3Contenedor.add(jPanelTop10, "card2");

        jComboBoxSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1-Enero-Junio", "2-Julio-Diciembre" }));

        jLabel3.setText("Seleccione el semestre:");

        jLabel4.setText("Ingreser el año:");

        jButtonVisualizarMenosDeseados.setText("Visualizar");
        jButtonVisualizarMenosDeseados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarMenosDeseadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenosDeseadosLayout = new javax.swing.GroupLayout(jPanelMenosDeseados);
        jPanelMenosDeseados.setLayout(jPanelMenosDeseadosLayout);
        jPanelMenosDeseadosLayout.setHorizontalGroup(
            jPanelMenosDeseadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenosDeseadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenosDeseadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelMenosDeseadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenosDeseadosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jButtonVisualizarMenosDeseados)
                        .addContainerGap())
                    .addGroup(jPanelMenosDeseadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAño1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelMenosDeseadosLayout.setVerticalGroup(
            jPanelMenosDeseadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenosDeseadosLayout.createSequentialGroup()
                .addGroup(jPanelMenosDeseadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenosDeseadosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelMenosDeseadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMenosDeseadosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonVisualizarMenosDeseados)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenosDeseadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3Contenedor.add(jPanelMenosDeseados, "card2");

        jLabel6.setText("Ingreser el año:");

        jButtonVisualizarEmpleadoMes.setText("Visualizar");
        jButtonVisualizarEmpleadoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarEmpleadoMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmpleadoMesLayout = new javax.swing.GroupLayout(jPanelEmpleadoMes);
        jPanelEmpleadoMes.setLayout(jPanelEmpleadoMesLayout);
        jPanelEmpleadoMesLayout.setHorizontalGroup(
            jPanelEmpleadoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoMesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldAño2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButtonVisualizarEmpleadoMes)
                .addGap(24, 24, 24))
        );
        jPanelEmpleadoMesLayout.setVerticalGroup(
            jPanelEmpleadoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoMesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelEmpleadoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVisualizarEmpleadoMes)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldAño2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel3Contenedor.add(jPanelEmpleadoMes, "card2");

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jPanel3Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(jPanel3Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String seleccion = this.jComboBoxBusqueda.getSelectedItem().toString();
        reportes = new Reportes();
        
        if (seleccion.equalsIgnoreCase("Seleccione")){
            JOptionPane.showMessageDialog(null, "Ingrese el reporte que desea generar", "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
        else if (seleccion.equalsIgnoreCase("Items de la carta más vendidos en el mes")) {
            
            mostrarPanel(this.jPanelTop10);
        }
        else if (seleccion.equalsIgnoreCase("Items de la carta menos vendidos en el semestre")){
            mostrarPanel(this.jPanelMenosDeseados);
        }
        else if (seleccion.equalsIgnoreCase("Tiempo promedio de atención de pedidos")){
            
            
        }
        else if (seleccion.equalsIgnoreCase("Ingresos en caja de cada día de la semana")){
            
        }
        else if (seleccion.equalsIgnoreCase("Reporte anual del mesero del mes")){
            mostrarPanel(this.jPanelEmpleadoMes);
            
        }
        else if (seleccion.equalsIgnoreCase("Ingresos en caja de cada día del mes")){
            mostrarPanel(this.jPanelTop10);
        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed
        
        int castMes=0, castAño=0;
        String mes=this.jComboBoxMes.getSelectedItem().toString();
        String año= this.jTextFieldAño.getText();
        if (mes=="Seleccione" || año==""){
            JOptionPane.showMessageDialog(null, "Ingrese los datos de busqueda", "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            mes=mes.substring(0, 2);
            try{
                castAño=Integer.parseInt(año);
                castMes=Integer.parseInt(mes);
                if (this.jComboBoxBusqueda.getSelectedItem().toString().equals("Items de la carta más vendidos en el mes")){
                    System.out.print("entro");
                    reportes.reporte10Mejores(castMes, castAño);
                    System.out.print("entro");
                }
                else if (this.jComboBoxBusqueda.getSelectedItem().toString().equals("Ingresos en caja de cada día del mes")){
                    System.out.print("entro");
                    reportes.reporteCajaMensual(castMes, castAño);
                }
                this.jTextFieldAño.setText("");
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese correctamente el año", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        }
    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    private void jButtonVisualizarMenosDeseadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarMenosDeseadosActionPerformed
        int castSemestre=0, castAño=0;
        String semestre=this.jComboBoxSemestre.getSelectedItem().toString();
        String año= this.jTextFieldAño1.getText();
        if (semestre=="Seleccione" || año==""){
            JOptionPane.showMessageDialog(null, "Ingrese los datos de busqueda", "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            semestre=semestre.substring(0, 1);
            try{
                castAño=Integer.parseInt(año);
                reportes.menosDeseados(semestre, castAño);
                this.jTextFieldAño1.setText("");
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese correctamente el año", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        }
    }//GEN-LAST:event_jButtonVisualizarMenosDeseadosActionPerformed

    private void jButtonVisualizarEmpleadoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarEmpleadoMesActionPerformed
        int castAño=0;
        String año=this.jTextFieldAño2.getText();
        if (año==""){
            JOptionPane.showMessageDialog(null, "Ingrese el año que desea consultar", "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                castAño=Integer.parseInt(año);
                reportes.reporteEmpleadoMes(castAño);
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese correctamente el año", "Error", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldAño2.setText("");
            }
        }
    }//GEN-LAST:event_jButtonVisualizarEmpleadoMesActionPerformed

    private void jComboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_VerReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_VerReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_VerReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_VerReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_VerReportes(new Gui_VentanaPrincipalGerente(new Gui_login())).setVisible(true);
               // new Gui_VerReportes(new Gui_VentanaPrincipalGerente(new Gui_login())).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JButton jButtonVisualizarEmpleadoMes;
    private javax.swing.JButton jButtonVisualizarMenosDeseados;
    private javax.swing.JComboBox<String> jComboBoxBusqueda;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxSemestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3Contenedor;
    private javax.swing.JPanel jPanelEmpleadoMes;
    private javax.swing.JPanel jPanelMenosDeseados;
    private javax.swing.JPanel jPanelTop10;
    private javax.swing.JTextField jTextFieldAño;
    private javax.swing.JTextField jTextFieldAño1;
    private javax.swing.JTextField jTextFieldAño2;
    // End of variables declaration//GEN-END:variables
 //

    public void reporteGerente() {
        this.jComboBoxBusqueda.addItem("Items de la carta más vendidos en el mes");
        this.jComboBoxBusqueda.addItem("Items de la carta menos vendidos en el semestre");
        this.jComboBoxBusqueda.addItem("Tiempo promedio de atención de pedidos");
        this.jComboBoxBusqueda.addItem("Ingresos en caja de cada día de la semana");
        this.jComboBoxBusqueda.addItem("Reporte anual del mesero del mes");
        this.jComboBoxBusqueda.addItem("Ingresos en caja de cada día del mes");
    }

    public void reporteContador() {
        this.jComboBoxBusqueda.addItem("Items de la carta más vendidos en el mes");
        this.jComboBoxBusqueda.addItem("Items de la carta menos vendidos en el semestre");
        this.jComboBoxBusqueda.addItem("Ingresos en caja de cada día de la semana");
        this.jComboBoxBusqueda.addItem("Ingresos en caja de cada día del mes");
    }

    public void reporteMesero() {
        this.jComboBoxBusqueda.addItem("Items de la carta más vendidos en el mes");
        this.jComboBoxBusqueda.addItem("Items de la carta menos vendidos en el semestre");
        this.jComboBoxBusqueda.addItem("Tiempo promedio de atención de pedidos");
        this.jComboBoxBusqueda.addItem("Reporte anual del mesero del mes");
    }
    
    public void mostrarPanel(JPanel panel){
        
        //eliminar panel contenedor
        this.jPanel3Contenedor.removeAll();
        this.jPanel3Contenedor.repaint();
        this.jPanel3Contenedor.revalidate();
        
        //añadir panel 
        this.jPanel3Contenedor.add(panel);
        this.jPanel3Contenedor.repaint();
        this.jPanel3Contenedor.revalidate();
        
        //mostrar panel
        this.jPanel3Contenedor.setVisible(true);
    }
}
